version: '3'

services:
  redis:
    container_name: redis
    build:
      context: redis
      target: dev
    volumes:
      - ./redis/logs:/var/log/redis
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always