version: '3.5'

services:
  server:
    container_name: server
    env_file:
      - dev.env
    build: 
      context: .
      target: dev
    volumes:
      - ./logs:/var/log/server
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    build:
      context: redis
      target: dev
    volumes:
      - ./redis/logs:/var/log/redis
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always

  nginx:
    container_name: nginx
    build:
      context: nginx
      target: dev
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    restart: always